### ISSUE TITLE
🎂 [Release] Release v3.1.2-581 - Chat, Fix Search, DKIM, etc.

### ISSUE THREAD

**Issue by Tirokk** [sender-fm/sender.fm#1]
# 🎂 Release

### Todos

- [ ] filters are not visible
- [x] adjust groups description length to `3`?
- [ ] change domain settings to administer by DO?
- [ ] footer pages like `data privacy` etc.
- [x] set new version and build number
- [x] still no(!) public registration!

**Comment by Tirokk** [comment]
don by #2
